const std = @import("std");

pub const Color = enum(usize) {
    reset = 0,
    bold = 1,
    dim = 2,
    italic = 3,
    underline = 4,
    blink = 5,
    inverse = 7,
    hidden = 8,
    strikethrough = 9,
    fg_black = 30,
    fg_red = 31,
    fg_green = 32,
    fg_yellow = 33,
    fg_blue = 34,
    fg_magenta = 35,
    fg_cyan = 36,
    fg_white = 37,
    fg_default = 39,
    fg_light_black = 90,
    fg_light_red = 91,
    fg_light_green = 92,
    fg_light_yellow = 93,
    fg_light_blue = 94,
    fg_light_magenta = 95,
    fg_light_cyan = 96,
    fg_light_white = 97,
    bg_black = 40,
    bg_red = 41,
    bg_green = 42,
    bg_yellow = 43,
    bg_blue = 44,
    bg_magenta = 45,
    bg_cyan = 46,
    bg_white = 47,
    bg_default = 49,
    bg_light_black = 100,
    bg_light_red = 101,
    bg_light_green = 102,
    bg_light_yellow = 103,
    bg_light_blue = 104,
    bg_light_magenta = 105,
    bg_light_cyan = 106,
    bg_light_white = 107,
};

pub const LogoInfo = struct {
    names: []const []const u8,
    colors: []const Color,

    pub fn init(names: []const []const u8, colors: []const Color) LogoInfo {
        return LogoInfo{
            .names = names,
            .colors = colors,
        };
    }

    pub fn matchNames(self: LogoInfo, name: []const u8) bool {
        for (self.names) |n| {
            if (std.mem.eql(u8, n, name)) {
                return true;
            }
        }
        return false;
    }
};

pub const logos = [_]LogoInfo{
    LogoInfo.init(&.{ "adélie", "adelie" }, &.{ .fg_blue, .fg_white, .fg_cyan }),
    LogoInfo.init(&.{"aeros"}, &.{ .fg_cyan, .fg_cyan }),
    LogoInfo.init(&.{"afterglow"}, &.{ .fg_magenta, .fg_red, .fg_yellow, .fg_blue }),
    LogoInfo.init(&.{ "z/os", "zos" }, &.{.fg_blue}),
    LogoInfo.init(&.{ "zorin", "zorin-linux", "zorinos", "zorinos-linux" }, &.{.fg_blue}),
    LogoInfo.init(&.{ "alpine", "alpinelinux", "alpine-linux" }, &.{.fg_blue}),
    LogoInfo.init(&.{"xray_os"}, &.{}),
    LogoInfo.init(&.{"xferience"}, &.{ .fg_cyan, .fg_cyan }),
    LogoInfo.init(&.{"alter"}, &.{.fg_cyan}),
    LogoInfo.init(&.{"xenia"}, &.{ .fg_yellow, .fg_green, .fg_red }),
    LogoInfo.init(&.{"amazon"}, &.{ .fg_yellow, .fg_white }),
    LogoInfo.init(&.{ "windows", "windows 7", "windows server 2008", "windows server 2008 r2" }, &.{ .fg_red, .fg_green, .fg_blue, .fg_yellow }),
    LogoInfo.init(&.{ "void", "void-linux" }, &.{ .fg_green, .fg_black }),
    LogoInfo.init(&.{"anarchy"}, &.{ .fg_white, .fg_blue }),
    LogoInfo.init(&.{"android"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"venom"}, &.{ .fg_light_black, .fg_blue }),
    LogoInfo.init(&.{"antergos"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{ "vanilla", "vanilla-os", "vanilla-linux" }, &.{.fg_yellow}),
    LogoInfo.init(&.{ "aosc os/retro", "aoscosretro" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"uwuntu"}, &.{}),
    LogoInfo.init(&.{ "aosc os", "aoscos" }, &.{ .fg_blue, .fg_black, .fg_red, .fg_yellow }),
    LogoInfo.init(&.{ "aosc os_old", "aoscos_old" }, &.{.fg_white}),
    LogoInfo.init(&.{"aperture"}, &.{.fg_cyan}),
    LogoInfo.init(&.{"urukos"}, &.{ .fg_light_blue, .fg_light_blue, .fg_white, .fg_light_blue, .fg_blue }),
    LogoInfo.init(&.{"uos"}, &.{.fg_red}),
    LogoInfo.init(&.{"apricity"}, &.{.fg_white}),
    LogoInfo.init(&.{"univention"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "ultramarine", "ultramarine linux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "ubuntu", "ubuntu-linux" }, &.{ .fg_red, .fg_red }),
    LogoInfo.init(&.{ "arch", "archlinux", "arch-linux", "archmerge" }, &.{ .fg_cyan, .fg_cyan }),
    LogoInfo.init(&.{"twister"}, &.{ .fg_green, .fg_red, .fg_blue, .fg_magenta, .fg_white }),
    LogoInfo.init(&.{"trisquel"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"torizoncore"}, &.{ .fg_light_white, .fg_yellow, .fg_blue }),
    LogoInfo.init(&.{"archlabs"}, &.{ .fg_cyan, .fg_red }),
    LogoInfo.init(&.{"archstrike"}, &.{ .fg_cyan, .fg_black }),
    LogoInfo.init(&.{"tileos"}, &.{ .fg_magenta, .fg_blue, .fg_green }),
    LogoInfo.init(&.{"armbian"}, &.{ .fg_white, .fg_red }),
    LogoInfo.init(&.{"armbian2"}, &.{.fg_red}),
    LogoInfo.init(&.{"tearch"}, &.{.fg_white}),
    LogoInfo.init(&.{"tatra"}, &.{ .fg_blue, .fg_green }),
    LogoInfo.init(&.{"tails"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "arco", "arcolinux", "arco-linux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"t2"}, &.{ .fg_white, .fg_blue }),
    LogoInfo.init(&.{"swagarch"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"arya"}, &.{ .fg_green, .fg_red }),
    LogoInfo.init(&.{ "asahi", "asahi-linux" }, &.{ .fg_yellow, .fg_green, .fg_red, .fg_light_black, .fg_white, .fg_cyan, .fg_blue }),
    LogoInfo.init(&.{ "suse", "suse-linux" }, &.{ .fg_green, .fg_green }),
    LogoInfo.init(&.{"aster"}, &.{.fg_cyan}),
    LogoInfo.init(&.{"asteroidos"}, &.{}),
    LogoInfo.init(&.{"astos"}, &.{.fg_white}),
    LogoInfo.init(&.{"sulin"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"steamos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"athena"}, &.{ .fg_white, .fg_yellow }),
    LogoInfo.init(&.{"azos"}, &.{ .fg_cyan, .fg_red }),
    LogoInfo.init(&.{ "bedrock", "bedrocklinux", "bedrock-linux" }, &.{.fg_light_black}),
    LogoInfo.init(&.{"star"}, &.{ .fg_white, .fg_white }),
    LogoInfo.init(&.{"bitrig"}, &.{.fg_green}),
    LogoInfo.init(&.{"blackarch"}, &.{ .fg_red, .fg_light_red, .fg_black }),
    LogoInfo.init(&.{ "blackmesa", "black-mesa" }, &.{.fg_black}),
    LogoInfo.init(&.{"blackpanther"}, &.{ .fg_red, .fg_yellow, .fg_light_blue }),
    LogoInfo.init(&.{"blag"}, &.{.fg_magenta}),
    LogoInfo.init(&.{"blankon"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"sparky"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"bodhi"}, &.{ .fg_white, .fg_light_yellow, .fg_green }),
    LogoInfo.init(&.{"bonsai"}, &.{ .fg_cyan, .fg_green, .fg_yellow }),
    LogoInfo.init(&.{"bsd"}, &.{ .fg_red, .fg_white, .fg_blue, .fg_yellow, .fg_cyan }),
    LogoInfo.init(&.{"bunsenlabs"}, &.{.fg_white}),
    LogoInfo.init(&.{ "cachy", "cachyos", "cachy-linux", "cachyos-linux" }, &.{ .fg_cyan, .fg_green, .fg_black }),
    LogoInfo.init(&.{ "solus", "solus-linux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"calculate"}, &.{ .fg_white, .fg_yellow }),
    LogoInfo.init(&.{ "calinix", "calinixos" }, &.{.fg_magenta}),
    LogoInfo.init(&.{ "solaris", "sunos" }, &.{.fg_yellow}),
    LogoInfo.init(&.{"carbs"}, &.{.fg_magenta}),
    LogoInfo.init(&.{ "source mage", "source mage gnu/linux", "source_mage", "sourcemage" }, &.{.fg_white}),
    LogoInfo.init(&.{ "cel", "celos", "cel-linux", "celos-linux" }, &.{ .fg_magenta, .fg_black }),
    LogoInfo.init(&.{"center"}, &.{.fg_white}),
    LogoInfo.init(&.{ "cent", "centos", "cent-linux", "centos-linux" }, &.{ .fg_yellow, .fg_green, .fg_blue, .fg_magenta, .fg_white }),
    LogoInfo.init(&.{"soda"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "cereus", "cereus linux" }, &.{}),
    LogoInfo.init(&.{"chakra"}, &.{.fg_blue}),
    LogoInfo.init(&.{"chaletos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"chapeau"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"smartos"}, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{ "slackware", "slackware-linux", "slackwarelinux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "chrom", "chromeos" }, &.{ .fg_green, .fg_red, .fg_yellow, .fg_blue, .fg_white }),
    LogoInfo.init(&.{"cleanjaro"}, &.{.fg_white}),
    LogoInfo.init(&.{"slackel"}, &.{ .fg_yellow, .fg_yellow }),
    LogoInfo.init(&.{ "spoinkos", "spoink-os" }, &.{.fg_green}),
    LogoInfo.init(&.{"clearos"}, &.{.fg_green}),
    LogoInfo.init(&.{"clover"}, &.{ .fg_green, .fg_cyan }),
    LogoInfo.init(&.{"slitaz"}, &.{ .fg_yellow, .fg_yellow }),
    LogoInfo.init(&.{"condres"}, &.{ .fg_green, .fg_yellow, .fg_cyan }),
    LogoInfo.init(&.{"skiffos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"siduction"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"shastraos"}, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{ "crystal", "crystal", "crystal-linux", "crystal-linux" }, &.{.fg_magenta}),
    LogoInfo.init(&.{ "cucumber", "cucumberos" }, &.{ .fg_green, .fg_yellow }),
    LogoInfo.init(&.{ "cuerdos", "cuerdos gnu/linux" }, &.{ .fg_yellow, .fg_green }),
    LogoInfo.init(&.{"cutefishos"}, &.{ .fg_cyan, .fg_white, .fg_blue }),
    LogoInfo.init(&.{"cuteos"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"cyberos"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"cycledream"}, &.{.fg_magenta}),
    LogoInfo.init(&.{"serene"}, &.{ .fg_cyan, .fg_cyan }),
    LogoInfo.init(&.{"darkos"}, &.{ .fg_red, .fg_cyan, .fg_magenta, .fg_yellow, .fg_green }),
    LogoInfo.init(&.{ "debian", "debian-linux" }, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"septor"}, &.{ .fg_blue, .fg_white, .fg_blue }),
    LogoInfo.init(&.{ "deepin", "deepin-linux" }, &.{.fg_green}),
    LogoInfo.init(&.{"desaos"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{ "devuan", "devuan-linux" }, &.{.fg_magenta}),
    LogoInfo.init(&.{"semc"}, &.{ .fg_green, .fg_light_black, .fg_red }),
    LogoInfo.init(&.{"dietpi"}, &.{ .fg_green, .fg_black }),
    LogoInfo.init(&.{"dracos"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "dragonfly", "dragonfly-bsd" }, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"scientific"}, &.{ .fg_blue, .fg_white, .fg_red }),
    LogoInfo.init(&.{"sasanqua"}, &.{ .fg_magenta, .fg_red }),
    LogoInfo.init(&.{ "draugeros", "drauger" }, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"droidian"}, &.{ .fg_green, .fg_light_green }),
    LogoInfo.init(&.{"elbrus"}, &.{.fg_blue}),
    LogoInfo.init(&.{"elementary"}, &.{.fg_white}),
    LogoInfo.init(&.{ "salient os", "salientos" }, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{"elive"}, &.{ .fg_white, .fg_light_cyan, .fg_cyan }),
    LogoInfo.init(&.{"encryptos"}, &.{.fg_magenta}),
    LogoInfo.init(&.{ "endeavour", "endeavour-linux", "endeavouros", "endeavouros-linux" }, &.{ .fg_magenta, .fg_red, .fg_blue }),
    LogoInfo.init(&.{"salentos"}, &.{ .fg_green, .fg_red, .fg_yellow, .fg_white }),
    LogoInfo.init(&.{"endless"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"enso"}, &.{.fg_white}),
    LogoInfo.init(&.{"eshanizedos"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"sailfish"}, &.{ .fg_blue, .fg_magenta }),
    LogoInfo.init(&.{"sabotage"}, &.{.fg_white}),
    LogoInfo.init(&.{"evolutionos"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"sabayon"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "rosa", "rosa-linux", "rosalinux" }, &.{.fg_blue}),
    LogoInfo.init(&.{ "exherbo", "exherbo-linux" }, &.{ .fg_blue, .fg_white, .fg_red }),
    LogoInfo.init(&.{ "rocky", "rocky-linux", "rockylinux" }, &.{.fg_green}),
    LogoInfo.init(&.{ "fedora", "fedora-linux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"rhaymos"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"regolith"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "fedora_old", "fedora-old", "fedora-linux-old", "fedora-linux_old" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "fedora_silverblue", "fedora-silverblue", "fedora-linux-silverblue", "fedora-linux_silverblue" }, &.{ .fg_blue, .fg_white, .fg_cyan }),
    LogoInfo.init(&.{ "fedora_kinoite", "fedora-kinoite", "fedora-linux-kinoite", "fedora-linux_kinoite" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "fedora_sericea", "fedora-sericea", "fedora-linux-sericea", "fedora-linux_sericea" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "fedora_coreos", "fedora-coreos", "fedora-linux-coreos", "fedora-linux_coreos" }, &.{ .fg_blue, .fg_white, .fg_red }),
    LogoInfo.init(&.{"regata"}, &.{ .fg_white, .fg_red, .fg_blue, .fg_magenta, .fg_yellow, .fg_green }),
    LogoInfo.init(&.{"feren"}, &.{.fg_blue}),
    LogoInfo.init(&.{ "redstar", "redstar-os", "redstaros", "redstaros-linux", "redstar-os-linux" }, &.{.fg_red}),
    LogoInfo.init(&.{"floflis"}, &.{.fg_light_cyan}),
    LogoInfo.init(&.{"freebsd"}, &.{ .fg_white, .fg_red }),
    LogoInfo.init(&.{ "redos", "red os", "red-os", "redos" }, &.{}),
    LogoInfo.init(&.{ "rhel", "redhat", "redhat-linux" }, &.{.fg_red}),
    LogoInfo.init(&.{ "frugalware", "frugalware-linux" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"funtoo"}, &.{ .fg_magenta, .fg_white }),
    LogoInfo.init(&.{"redcore"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"galliumos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "garuda", "garuda-linux" }, &.{.fg_red}),
    LogoInfo.init(&.{ "reborn", "reborn os", "reborn-os", "rebornos", "rebornos-linux", "reborn-os-linux" }, &.{ .fg_black, .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"ravynos"}, &.{.fg_white}),
    LogoInfo.init(&.{ "gentoo", "gentoo-linux" }, &.{ .fg_magenta, .fg_white }),
    LogoInfo.init(&.{ "raspbian", "raspi", "raspberrypi", "raspberrypios" }, &.{ .fg_red, .fg_green }),
    LogoInfo.init(&.{"ghostbsd"}, &.{.fg_blue}),
    LogoInfo.init(&.{"glaucus"}, &.{.fg_magenta}),
    LogoInfo.init(&.{"gnewsense"}, &.{.fg_blue}),
    LogoInfo.init(&.{"gnome"}, &.{.fg_blue}),
    LogoInfo.init(&.{"gnu"}, &.{.fg_white}),
    LogoInfo.init(&.{"quibian"}, &.{ .fg_yellow, .fg_white }),
    LogoInfo.init(&.{"qubes"}, &.{ .fg_blue, .fg_magenta }),
    LogoInfo.init(&.{"grapheneos"}, &.{.fg_white}),
    LogoInfo.init(&.{"grombyang"}, &.{ .fg_blue, .fg_green, .fg_red }),
    LogoInfo.init(&.{"q4os"}, &.{ .fg_blue, .fg_red }),
    LogoInfo.init(&.{"pureos"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"haiku"}, &.{ .fg_red, .fg_yellow, .fg_white, .fg_green }),
    LogoInfo.init(&.{"puppy"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"hamonikr"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"hardclanz"}, &.{ .fg_blue, .fg_white, .fg_red }),
    LogoInfo.init(&.{"puffos"}, &.{ .fg_yellow, .fg_white }),
    LogoInfo.init(&.{"hash"}, &.{}),
    LogoInfo.init(&.{"postmarketos"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"huayra"}, &.{.fg_white}),
    LogoInfo.init(&.{"hybrid"}, &.{ .fg_blue, .fg_light_blue }),
    LogoInfo.init(&.{"hydroos"}, &.{.fg_red}),
    LogoInfo.init(&.{"porteus"}, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{"hyperbola"}, &.{.fg_light_black}),
    LogoInfo.init(&.{ "pop", "popos", "pop_os", "pop-linux" }, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{"pisi"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"instantos"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"pikaos"}, &.{.fg_yellow}),
    LogoInfo.init(&.{"phyos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"ironclad"}, &.{.fg_black}),
    LogoInfo.init(&.{"itc"}, &.{.fg_red}),
    LogoInfo.init(&.{ "peropesis", "peropesis linux" }, &.{.fg_white}),
    LogoInfo.init(&.{"kaisen"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "kali", "kalilinux" }, &.{ .fg_blue, .fg_light_black }),
    LogoInfo.init(&.{"pentoo"}, &.{ .fg_magenta, .fg_white }),
    LogoInfo.init(&.{"kaos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"kernelos"}, &.{ .fg_red, .fg_magenta }),
    LogoInfo.init(&.{ "kde", "kde-neon", "kde neon" }, &.{.fg_green}),
    LogoInfo.init(&.{"kibojoe"}, &.{ .fg_green, .fg_white, .fg_blue }),
    LogoInfo.init(&.{ "kiss", "kiss-linux", "kisslinux" }, &.{ .fg_magenta, .fg_white, .fg_blue }),
    LogoInfo.init(&.{"kogaion"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"korora"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "krassos", "krass" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"pengwin"}, &.{ .fg_magenta, .fg_light_magenta, .fg_magenta }),
    LogoInfo.init(&.{ "kubuntu", "kubuntu-linux", "kde-ubuntu" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"lainos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "langitketujuh", "l7" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"laxeros"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"lede"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"libreelec"}, &.{ .fg_green, .fg_yellow, .fg_white, .fg_cyan, .fg_magenta }),
    LogoInfo.init(&.{"pearos"}, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }),
    LogoInfo.init(&.{ "linspire", "lindows" }, &.{ .fg_blue, .fg_green }),
    LogoInfo.init(&.{"pclinuxos"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "pcbsd", "trueos" }, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"pardus"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{ "linuxlite", "linux lite", "linux_lite" }, &.{ .fg_yellow, .fg_white }),
    LogoInfo.init(&.{"parch"}, &.{ .fg_blue, .fg_white, .fg_red }),
    LogoInfo.init(&.{ "parabola", "parabola-gnulinux" }, &.{.fg_magenta}),
    LogoInfo.init(&.{"panwah"}, &.{ .fg_white, .fg_red, .fg_black }),
    LogoInfo.init(&.{"pacbsd"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{ "live raizo", "live_raizo" }, &.{.fg_yellow}),
    LogoInfo.init(&.{ "osmc", "open source media center" }, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"lmde"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{ "locos", "loc-os", "loc-os linux" }, &.{ .fg_black, .fg_yellow, .fg_white }),
    LogoInfo.init(&.{"lunar"}, &.{ .fg_blue, .fg_white, .fg_yellow }),
    LogoInfo.init(&.{ "macos", "mac" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }),
    LogoInfo.init(&.{"orchid"}, &.{ .fg_white, .fg_magenta, .fg_magenta }),
    LogoInfo.init(&.{ "macos2", "mac2" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }),
    LogoInfo.init(&.{ "oracle", "oracle linux", "oracle linux server" }, &.{.fg_red}),
    LogoInfo.init(&.{ "macos3", "mac3" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }),
    LogoInfo.init(&.{"mainsailos"}, &.{.fg_red}),
    LogoInfo.init(&.{"opnsense"}, &.{.fg_white}),
    LogoInfo.init(&.{"mageia"}, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{ "openmandriva", "open-mandriva", "open_mandriva", "openmandriva lx" }, &.{.fg_blue}),
    LogoInfo.init(&.{ "opensuse_slowroll", "opensuse-slowroll", "opensuse-tumbleweed-slowroll" }, &.{.fg_white}),
    LogoInfo.init(&.{ "magpieos", "magpie" }, &.{ .fg_green, .fg_red, .fg_yellow, .fg_magenta }),
    LogoInfo.init(&.{ "mandriva", "mandrake" }, &.{ .fg_blue, .fg_yellow }),
    LogoInfo.init(&.{ "manjaro", "manjaro-linux", "manjarolinux", "manjaro-arm" }, &.{.fg_green}),
    LogoInfo.init(&.{ "opensuse_tumbleweed", "open_suse_tumbleweed", "opensuse-tumbleweed", "open-suse-tumbleweed", "suse_tumbleweed", "suse-tumbleweed", "opensusetumbleweed" }, &.{.fg_white}),
    LogoInfo.init(&.{ "massos", "mass" }, &.{.fg_white}),
    LogoInfo.init(&.{ "matuusos", "matuus" }, &.{ .fg_yellow, .fg_red }),
    LogoInfo.init(&.{"maui"}, &.{.fg_cyan}),
    LogoInfo.init(&.{"mauna"}, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{ "opensuse_leap", "open_suse_leap", "opensuse-leap", "open-suse-leap", "suse_leap", "suse-leap", "opensuseleap" }, &.{.fg_white}),
    LogoInfo.init(&.{"mer"}, &.{.fg_blue}),
    LogoInfo.init(&.{ "opensuse-microos", "opensuse_microos" }, &.{.fg_green}),
    LogoInfo.init(&.{ "opensuse", "open_suse", "open-suse" }, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"openstage"}, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{"openmamba"}, &.{ .fg_white, .fg_green }),
    LogoInfo.init(&.{"openindiana"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"mos"}, &.{ .fg_cyan, .fg_blue }),
    LogoInfo.init(&.{"msys2"}, &.{ .fg_magenta, .fg_white, .fg_red }),
    LogoInfo.init(&.{"openeuler"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{"openbsd"}, &.{ .fg_yellow, .fg_white, .fg_cyan, .fg_red }),
    LogoInfo.init(&.{"mx2"}, &.{.fg_white}),
    LogoInfo.init(&.{"namib"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"nekos"}, &.{ .fg_yellow, .fg_white, .fg_red }),
    LogoInfo.init(&.{"neptune"}, &.{ .fg_white, .fg_white }),
    LogoInfo.init(&.{"netrunner"}, &.{ .fg_blue, .fg_white }),
    LogoInfo.init(&.{ "openkylin", "open-kylin" }, &.{ .fg_green, .fg_white }),
    LogoInfo.init(&.{ "nixos", "nix", "nixos-linux", "nix-linux" }, &.{ .fg_blue, .fg_cyan }),
    LogoInfo.init(&.{"omnios"}, &.{ .fg_white, .fg_yellow, .fg_light_black }),
    LogoInfo.init(&.{"obrevenge"}, &.{ .fg_red, .fg_white }),
    LogoInfo.init(&.{"obarun"}, &.{ .fg_cyan, .fg_white }),
    LogoInfo.init(&.{"netbsd"}, &.{ .fg_magenta, .fg_white }),
    LogoInfo.init(&.{ "nobara", "nobara-linux" }, &.{.fg_white}),
    LogoInfo.init(&.{"nomadbsd"}, &.{.fg_blue}),
    LogoInfo.init(&.{"nurunner"}, &.{ .fg_blue, .fg_white }),
};
