//==================================================================================================
// File:       info.zig
// Contents:   Information external to the OS used by the program.
// Author:     Will Carter
//==================================================================================================

const std = @import("std");

const LogoInfo = @import("./utils/logo.zig").LogoInfo;
const Color = @import("./utils/logo.zig").Color;

const VersionError = error{
    InvalidVersion,
    UnknownVersion,
};

pub fn darwinVersionName(version: []const u8) ![]const u8 {
    const version_ranges = &[_][2][]const u8{
        .{ "10.0", "Cheetah" },
        .{ "10.1", "Puma" },
        .{ "10.2", "Jaguar" },
        .{ "10.3", "Panther" },
        .{ "10.4", "Tiger" },
        .{ "10.5", "Leopard" },
        .{ "10.6", "Snow Leopard" },
        .{ "10.7", "Lion" },
        .{ "10.8", "Mountain Lion" },
        .{ "10.9", "Mavericks" },
        .{ "10.10", "Yosemite" },
        .{ "10.11", "El Capitan" },
        .{ "10.12", "Sierra" },
        .{ "10.13", "High Sierra" },
        .{ "10.14", "Mojave" },
        .{ "10.15", "Catalina" },
        .{ "11", "Big Sur" },
        .{ "12", "Monterey" },
        .{ "13", "Ventura" },
    };

    const parsed_version = std.fmt.parseFloat(f32, version) catch return VersionError.InvalidVersion;
    var previous_name: []const u8 = "";

    for (version_ranges) |range| {
        const range_version = std.fmt.parseFloat(f32, range[0]) catch return VersionError.InvalidVersion;
        if (parsed_version >= range_version) {
            previous_name = range[1];
        } else {
            break;
        }
    }

    if (previous_name.len == 0) {
        return VersionError.UnknownVersion;
    }

    return previous_name;
}

pub const products = .{
    // MacBook Pro
    .{ "MacBookPro18,3", "MacBook Pro (14-inch, 2021)" },
    .{ "MacBookPro18,4", "MacBook Pro (14-inch, 2021)" },
    .{ "MacBookPro18,1", "MacBook Pro (16-inch, 2021)" },
    .{ "MacBookPro18,2", "MacBook Pro (16-inch, 2021)" },
    .{ "MacBookPro17,1", "MacBook Pro (13-inch, M1, 2020)" },
    .{ "MacBookPro16,4", "MacBook Pro (16-inch, 2019)" },
    .{ "MacBookPro16,3", "MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)" },
    .{ "MacBookPro16,2", "MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)" },
    .{ "MacBookPro16,1", "MacBook Pro (16-inch, 2019)" },
    .{ "MacBookPro15,4", "MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)" },
    .{ "MacBookPro15,3", "MacBook Pro (15-inch, 2019)" },
    .{ "MacBookPro15,2", "MacBook Pro (13-inch, 2018/2019, Four Thunderbolt 3 ports)" },
    .{ "MacBookPro15,1", "MacBook Pro (15-inch, 2018/2019)" },
    .{ "MacBookPro14,3", "MacBook Pro (15-inch, 2017)" },
    .{ "MacBookPro14,2", "MacBook Pro (13-inch, 2017, Four Thunderbolt 3 ports)" },
    .{ "MacBookPro14,1", "MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)" },
    .{ "MacBookPro13,3", "MacBook Pro (15-inch, 2016)" },
    .{ "MacBookPro13,2", "MacBook Pro (13-inch, 2016, Four Thunderbolt 3 ports)" },
    .{ "MacBookPro13,1", "MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)" },
    .{ "MacBookPro12,1", "MacBook Pro (Retina, 13-inch, Early 2015)" },
    .{ "MacBookPro11,4", "MacBook Pro (Retina, 15-inch, Mid 2015)" },
    .{ "MacBookPro11,5", "MacBook Pro (Retina, 15-inch, Mid 2015)" },
    .{ "MacBookPro11,2", "MacBook Pro (Retina, 15-inch, Late 2013/Mid 2014)" },
    .{ "MacBookPro11,3", "MacBook Pro (Retina, 15-inch, Late 2013/Mid 2014)" },
    .{ "MacBookPro11,1", "MacBook Pro (Retina, 13-inch, Late 2013/Mid 2014)" },
    .{ "MacBookPro10,2", "MacBook Pro (Retina, 13-inch, Late 2012/Early 2013)" },
    .{ "MacBookPro10,1", "MacBook Pro (Retina, 15-inch, Mid 2012/Early 2013)" },
    .{ "MacBookPro9,2", "MacBook Pro (13-inch, Mid 2012)" },
    .{ "MacBookPro9,1", "MacBook Pro (15-inch, Mid 2012)" },
    .{ "MacBookPro8,3", "MacBook Pro (17-inch, 2011)" },
    .{ "MacBookPro8,2", "MacBook Pro (15-inch, 2011)" },
    .{ "MacBookPro8,1", "MacBook Pro (13-inch, 2011)" },
    .{ "MacBookPro7,1", "MacBook Pro (13-inch, Mid 2010)" },
    .{ "MacBookPro6,2", "MacBook Pro (15-inch, Mid 2010)" },
    .{ "MacBookPro6,1", "MacBook Pro (17-inch, Mid 2010)" },
    .{ "MacBookPro5,5", "MacBook Pro (13-inch, Mid 2009)" },
    .{ "MacBookPro5,3", "MacBook Pro (15-inch, Mid 2009)" },
    .{ "MacBookPro5,2", "MacBook Pro (17-inch, Mid/Early 2009)" },
    .{ "MacBookPro5,1", "MacBook Pro (15-inch, Late 2008)" },
    .{ "MacBookPro4,1", "MacBook Pro (17/15-inch, Early 2008)" },

    // MacBook Air
    .{ "MacBookAir10,1", "MacBook Air (M1, 2020)" },
    .{ "MacBookAir9,1", "MacBook Air (Retina, 13-inch, 2020)" },
    .{ "MacBookAir8,2", "MacBook Air (Retina, 13-inch, 2019)" },
    .{ "MacBookAir8,1", "MacBook Air (Retina, 13-inch, 2018)" },
    .{ "MacBookAir7,2", "MacBook Air (13-inch, Early 2015/2017)" },
    .{ "MacBookAir7,1", "MacBook Air (11-inch, Early 2015)" },
    .{ "MacBookAir6,2", "MacBook Air (13-inch, Mid 2013/Early 2014)" },
    .{ "MacBookAir6,1", "MacBook Air (11-inch, Mid 2013/Early 2014)" },
    .{ "MacBookAir5,2", "MacBook Air (13-inch, Mid 2012)" },
    .{ "MacBookAir5,1", "MacBook Air (11-inch, Mid 2012)" },
    .{ "MacBookAir4,2", "MacBook Air (13-inch, Mid 2011)" },
    .{ "MacBookAir4,1", "MacBook Air (11-inch, Mid 2011)" },
    .{ "MacBookAir3,2", "MacBook Air (13-inch, Late 2010)" },
    .{ "MacBookAir3,1", "MacBook Air (11-inch, Late 2010)" },
    .{ "MacBookAir2,1", "MacBook Air (Mid 2009)" },

    // Mac mini
    .{ "Macmini9,1", "Mac mini (M1, 2020)" },
    .{ "Macmini8,1", "Mac mini (2018)" },
    .{ "Macmini7,1", "Mac mini (Mid 2014)" },
    .{ "Macmini6,1", "Mac mini (Late 2012)" },
    .{ "Macmini6,2", "Mac mini (Late 2012)" },
    .{ "Macmini5,1", "Mac mini (Mid 2011)" },
    .{ "Macmini5,2", "Mac mini (Mid 2011)" },
    .{ "Macmini4,1", "Mac mini (Mid 2010)" },
    .{ "Macmini3,1", "Mac mini (Early/Late 2009)" },

    // MacBook
    .{ "MacBook10,1", "MacBook (Retina, 12-inch, 2017)" },
    .{ "MacBook9,1", "MacBook (Retina, 12-inch, Early 2016)" },
    .{ "MacBook8,1", "MacBook (Retina, 12-inch, Early 2015)" },
    .{ "MacBook7,1", "MacBook (13-inch, Mid 2010)" },
    .{ "MacBook6,1", "MacBook (13-inch, Late 2009)" },
    .{ "MacBook5,2", "MacBook (13-inch, Early/Mid 2009)" },

    // Mac Pro
    .{ "MacPro7,1", "Mac Pro (2019)" },
    .{ "MacPro6,1", "Mac Pro (Late 2013)" },
    .{ "MacPro5,1", "Mac Pro (Mid 2010 - Mid 2012)" },
    .{ "MacPro4,1", "Mac Pro (Early 2009)" },

    // iMac
    .{ "iMac21,1", "iMac (24-inch, M1, 2021, Two Thunderbolt / USB 4 ports, Two USB 3 ports)" },
    .{ "iMac21,2", "iMac (24-inch, M1, 2021, Two Thunderbolt / USB 4 ports)" },
    .{ "iMac20,1", "iMac (Retina 5K, 27-inch, 2020)" },
    .{ "iMac20,2", "iMac (Retina 5K, 27-inch, 2020)" },
    .{ "iMac19,1", "iMac (Retina 5K, 27-inch, 2019)" },
    .{ "iMac19,2", "iMac (Retina 4K, 21.5-inch, 2019)" },
    .{ "iMacPro1,1", "iMac Pro (2017)" },
    .{ "iMac18,3", "iMac (Retina 5K, 27-inch, 2017)" },
    .{ "iMac18,2", "iMac (Retina 4K, 21.5-inch, 2017)" },
    .{ "iMac18,1", "iMac (21.5-inch, 2017)" },
    .{ "iMac17,1", "iMac (Retina 5K, 27-inch, Late 2015)" },
    .{ "iMac16,2", "iMac (Retina 4K, 21.5-inch, Late 2015)" },
    .{ "iMac16,1", "iMac (21.5-inch, Late 2015)" },
    .{ "iMac15,1", "iMac (Retina 5K, 27-inch, Late 2014 - Mid 2015)" },
    .{ "iMac14,4", "iMac (21.5-inch, Mid 2014)" },
    .{ "iMac14,2", "iMac (27-inch, Late 2013)" },
    .{ "iMac14,1", "iMac (21.5-inch, Late 2013)" },
    .{ "iMac13,2", "iMac (27-inch, Late 2012)" },
    .{ "iMac13,1", "iMac (21.5-inch, Late 2012)" },
    .{ "iMac12,2", "iMac (27-inch, Mid 2011)" },
    .{ "iMac12,1", "iMac (21.5-inch, Mid 2011)" },
    .{ "iMac11,3", "iMac (27-inch, Mid 2010)" },
    .{ "iMac11,2", "iMac (21.5-inch, Mid 2010)" },
    .{ "iMac10,1", "iMac (27/21.5-inch, Late 2009)" },
    .{ "iMac9,1", "iMac (24/20-inch, Early 2009)" },

    // Newer models (2023-2024)
    .{ "Mac15,13", "MacBook Air (15-inch, M3, 2024)" },
    .{ "Mac15,2", "MacBook Air (13-inch, M3, 2024)" },
    .{ "Mac15,3", "MacBook Pro (14-inch, Nov 2023, Two Thunderbolt / USB 4 ports)" },
    .{ "Mac15,4", "iMac (24-inch, 2023, Two Thunderbolt / USB 4 ports)" },
    .{ "Mac15,5", "iMac (24-inch, 2023, Two Thunderbolt / USB 4 ports, Two USB 3 ports)" },
    .{ "Mac15,6", "MacBook Pro (14-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac15,8", "MacBook Pro (14-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac15,10", "MacBook Pro (14-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac15,7", "MacBook Pro (16-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac15,9", "MacBook Pro (16-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac15,11", "MacBook Pro (16-inch, Nov 2023, Three Thunderbolt 4 ports)" },
    .{ "Mac14,15", "MacBook Air (15-inch, M2, 2023)" },
    .{ "Mac14,14", "Mac Studio (M2 Ultra, 2023, Two Thunderbolt 4 front ports)" },
    .{ "Mac14,13", "Mac Studio (M2 Max, 2023, Two USB-C front ports)" },
    .{ "Mac14,8", "Mac Pro (2023)" },
    .{ "Mac14,6", "MacBook Pro (16-inch, 2023)" },
    .{ "Mac14,10", "MacBook Pro (16-inch, 2023)" },
    .{ "Mac14,5", "MacBook Pro (14-inch, 2023)" },
    .{ "Mac14,9", "MacBook Pro (14-inch, 2023)" },
    .{ "Mac14,3", "Mac mini (M2, 2023, Two Thunderbolt 4 ports)" },
    .{ "Mac14,12", "Mac mini (M2, 2023, Four Thunderbolt 4 ports)" },
    .{ "Mac14,7", "MacBook Pro (13-inch, M2, 2022)" },
    .{ "Mac14,2", "MacBook Air (M2, 2022)" },
    .{ "Mac13,1", "Mac Studio (M1 Max, 2022, Two USB-C front ports)" },
    .{ "Mac13,2", "Mac Studio (M1 Ultra, 2022, Two Thunderbolt 4 front ports)" },
};

pub const logo_list = [_]LogoInfo{
    LogoInfo.init(&.{ "adélie", "adelie" }, &.{ .fg_blue, .fg_white, .fg_cyan }, null, null),
    LogoInfo.init(&.{"aeros"}, &.{ .fg_cyan, .fg_cyan }, null, null),
    LogoInfo.init(&.{"afterglow"}, &.{ .fg_magenta, .fg_red, .fg_yellow, .fg_blue }, null, null),
    LogoInfo.init(&.{ "z/os", "zos" }, &.{.fg_blue}, null, null),
    LogoInfo.init(&.{ "zorin", "zorin-linux", "zorinos", "zorinos-linux" }, &.{.fg_blue}, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "alpine", "alpinelinux", "alpine-linux" }, &.{.fg_blue}, .fg_magenta, .fg_blue),
    LogoInfo.init(&.{"xray_os"}, &.{}, null, null),
    LogoInfo.init(&.{"xferience"}, &.{ .fg_cyan, .fg_cyan }, null, null),
    LogoInfo.init(&.{"alter"}, &.{.fg_cyan}, .fg_cyan, .fg_cyan),
    LogoInfo.init(&.{"xenia"}, &.{ .fg_yellow, .fg_green, .fg_red }, null, null),
    LogoInfo.init(&.{"amazon"}, &.{ .fg_yellow, .fg_white }, null, null),
    LogoInfo.init(&.{ "windows", "windows 7", "windows server 2008", "windows server 2008 r2" }, &.{ .fg_red, .fg_green, .fg_blue, .fg_yellow }, .fg_blue, .fg_green),
    LogoInfo.init(&.{ "void", "void-linux" }, &.{ .fg_green, .fg_black }, .fg_white, .fg_green),
    LogoInfo.init(&.{"anarchy"}, &.{ .fg_white, .fg_blue }, .fg_white, .fg_blue),
    LogoInfo.init(&.{"android"}, &.{ .fg_green, .fg_white }, .fg_green, .fg_green),
    LogoInfo.init(&.{"venom"}, &.{ .fg_light_black, .fg_blue }, null, null),
    LogoInfo.init(&.{"antergos"}, &.{ .fg_blue, .fg_cyan }, .fg_blue, .fg_cyan),
    LogoInfo.init(&.{ "vanilla", "vanilla-os", "vanilla-linux" }, &.{.fg_yellow}, .fg_yellow, .fg_yellow),
    LogoInfo.init(&.{ "aosc os/retro", "aoscosretro" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"uwuntu"}, &.{}, null, null),
    LogoInfo.init(&.{ "aosc os", "aoscos" }, &.{ .fg_blue, .fg_black, .fg_red, .fg_yellow }, null, null),
    LogoInfo.init(&.{ "aosc os_old", "aoscos_old" }, &.{.fg_white}, .fg_blue, .fg_white),
    LogoInfo.init(&.{"aperture"}, &.{.fg_cyan}, .fg_cyan, .fg_white),
    LogoInfo.init(&.{"urukos"}, &.{ .fg_light_blue, .fg_light_blue, .fg_white, .fg_light_blue, .fg_blue }, null, null),
    LogoInfo.init(&.{"uos"}, &.{.fg_red}, .fg_white, .fg_yellow),
    LogoInfo.init(&.{"apricity"}, &.{.fg_white}, .fg_blue, .fg_white),
    LogoInfo.init(&.{"univention"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{ "ultramarine", "ultramarine linux" }, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "ubuntu", "ubuntu-linux" }, &.{ .fg_red, .fg_red }, null, null),
    LogoInfo.init(&.{ "arch", "archlinux", "arch-linux", "archmerge" }, &.{ .fg_cyan, .fg_cyan }, null, null),
    LogoInfo.init(&.{"twister"}, &.{ .fg_green, .fg_red, .fg_blue, .fg_magenta, .fg_white }, null, null),
    LogoInfo.init(&.{"trisquel"}, &.{ .fg_blue, .fg_cyan }, null, null),
    LogoInfo.init(&.{"torizoncore"}, &.{ .fg_light_white, .fg_yellow, .fg_blue }, null, null),
    LogoInfo.init(&.{"archlabs"}, &.{ .fg_cyan, .fg_red }, .fg_cyan, .fg_red),
    LogoInfo.init(&.{"archstrike"}, &.{ .fg_cyan, .fg_black }, .fg_cyan, .fg_cyan),
    LogoInfo.init(&.{"tileos"}, &.{ .fg_magenta, .fg_blue, .fg_green }, null, null),
    LogoInfo.init(&.{"armbian"}, &.{ .fg_white, .fg_red }, null, null),
    LogoInfo.init(&.{"armbian2"}, &.{.fg_red}, null, null),
    LogoInfo.init(&.{"tearch"}, &.{.fg_white}, null, null),
    LogoInfo.init(&.{"tatra"}, &.{ .fg_blue, .fg_green }, null, null),
    LogoInfo.init(&.{"tails"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "arco", "arcolinux", "arco-linux" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"t2"}, &.{ .fg_white, .fg_blue }, null, null),
    LogoInfo.init(&.{"swagarch"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"arya"}, &.{ .fg_green, .fg_red }, .fg_green, .fg_red),
    LogoInfo.init(&.{ "asahi", "asahi-linux" }, &.{ .fg_yellow, .fg_green, .fg_red, .fg_light_black, .fg_white, .fg_cyan, .fg_blue }, .fg_yellow, .fg_green),
    LogoInfo.init(&.{ "suse", "suse-linux" }, &.{ .fg_green, .fg_green }, null, null),
    LogoInfo.init(&.{"aster"}, &.{.fg_cyan}, .fg_cyan, .fg_cyan),
    LogoInfo.init(&.{"asteroidos"}, &.{}, null, null),
    LogoInfo.init(&.{"astos"}, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{"sulin"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"steamos"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"athena"}, &.{ .fg_white, .fg_yellow }, .fg_yellow, .fg_white),
    LogoInfo.init(&.{"azos"}, &.{ .fg_cyan, .fg_red }, null, null),
    LogoInfo.init(&.{ "bedrock", "bedrocklinux", "bedrock-linux" }, &.{.fg_light_black}, null, .fg_white),
    LogoInfo.init(&.{"star"}, &.{ .fg_white, .fg_white }, null, null),
    LogoInfo.init(&.{"bitrig"}, &.{.fg_green}, .fg_white, .fg_green),
    LogoInfo.init(&.{"blackarch"}, &.{ .fg_red, .fg_light_red, .fg_black }, .fg_light_red, .fg_red),
    LogoInfo.init(&.{ "blackmesa", "black-mesa" }, &.{.fg_black}, .fg_black, .fg_white),
    LogoInfo.init(&.{"blackpanther"}, &.{ .fg_red, .fg_yellow, .fg_light_blue }, .fg_red, .fg_yellow),
    LogoInfo.init(&.{"blag"}, &.{.fg_magenta}, .fg_magenta, .fg_white),
    LogoInfo.init(&.{"blankon"}, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{"sparky"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"bodhi"}, &.{ .fg_white, .fg_light_yellow, .fg_green }, .fg_yellow, .fg_green),
    LogoInfo.init(&.{"bonsai"}, &.{ .fg_cyan, .fg_green, .fg_yellow }, .fg_cyan, .fg_green),
    LogoInfo.init(&.{"bsd"}, &.{ .fg_red, .fg_white, .fg_blue, .fg_yellow, .fg_cyan }, .fg_red, .fg_white),
    LogoInfo.init(&.{"bunsenlabs"}, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{ "cachy", "cachyos", "cachy-linux", "cachyos-linux" }, &.{ .fg_cyan, .fg_green, .fg_black }, .fg_cyan, .fg_cyan),
    LogoInfo.init(&.{ "solus", "solus-linux" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"calculate"}, &.{ .fg_white, .fg_yellow }, .fg_yellow, .fg_white),
    LogoInfo.init(&.{ "calinix", "calinixos" }, &.{.fg_magenta}, .fg_magenta, .fg_blue),
    LogoInfo.init(&.{ "solaris", "sunos" }, &.{.fg_yellow}, .fg_yellow, .fg_white),
    LogoInfo.init(&.{"carbs"}, &.{.fg_magenta}, .fg_magenta, .fg_blue),
    LogoInfo.init(&.{ "source mage", "source mage gnu/linux", "source_mage", "sourcemage" }, &.{.fg_white}, .fg_red, .fg_white),
    LogoInfo.init(&.{ "cel", "celos", "cel-linux", "celos-linux" }, &.{ .fg_magenta, .fg_black }, .fg_cyan, .fg_blue),
    LogoInfo.init(&.{"center"}, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{ "cent", "centos", "cent-linux", "centos-linux" }, &.{ .fg_yellow, .fg_green, .fg_blue, .fg_magenta, .fg_white }, .fg_green, .fg_yellow),
    LogoInfo.init(&.{"soda"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{ "cereus", "cereus linux" }, &.{}, null, null),
    LogoInfo.init(&.{"chakra"}, &.{.fg_blue}, .fg_blue, .fg_magenta),
    LogoInfo.init(&.{"chaletos"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"chapeau"}, &.{ .fg_green, .fg_white }, .fg_green, .fg_white),
    LogoInfo.init(&.{"smartos"}, &.{ .fg_cyan, .fg_white }, null, null),
    LogoInfo.init(&.{ "slackware", "slackware-linux", "slackwarelinux" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "chrom", "chromeos" }, &.{ .fg_green, .fg_red, .fg_yellow, .fg_blue, .fg_white }, .fg_green, .fg_red),
    LogoInfo.init(&.{"cleanjaro"}, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{"slackel"}, &.{ .fg_yellow, .fg_yellow }, null, null),
    LogoInfo.init(&.{ "spoinkos", "spoink-os" }, &.{.fg_green}, null, null),
    LogoInfo.init(&.{"clearos"}, &.{.fg_green}, .fg_green, .fg_green),
    LogoInfo.init(&.{"clover"}, &.{ .fg_green, .fg_cyan }, .fg_green, .fg_cyan),
    LogoInfo.init(&.{"slitaz"}, &.{ .fg_yellow, .fg_yellow }, null, null),
    LogoInfo.init(&.{"condres"}, &.{ .fg_green, .fg_yellow, .fg_cyan }, .fg_green, .fg_yellow),
    LogoInfo.init(&.{"skiffos"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"siduction"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"shastraos"}, &.{ .fg_cyan, .fg_white }, null, null),
    LogoInfo.init(&.{ "crystal", "crystal", "crystal-linux", "crystal-linux" }, &.{.fg_magenta}, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{ "cucumber", "cucumberos" }, &.{ .fg_green, .fg_yellow }, .fg_green, .fg_yellow),
    LogoInfo.init(&.{ "cuerdos", "cuerdos gnu/linux" }, &.{ .fg_yellow, .fg_green }, .fg_green, .fg_yellow),
    LogoInfo.init(&.{"cutefishos"}, &.{ .fg_cyan, .fg_white, .fg_blue }, null, null),
    LogoInfo.init(&.{"cuteos"}, &.{ .fg_blue, .fg_cyan }, .fg_blue, .fg_cyan),
    LogoInfo.init(&.{"cyberos"}, &.{ .fg_blue, .fg_cyan }, .fg_blue, .fg_cyan),
    LogoInfo.init(&.{"cycledream"}, &.{.fg_magenta}, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{"serene"}, &.{ .fg_cyan, .fg_cyan }, null, null),
    LogoInfo.init(&.{"darkos"}, &.{ .fg_red, .fg_cyan, .fg_magenta, .fg_yellow, .fg_green }, .fg_red, .fg_cyan),
    LogoInfo.init(&.{ "debian", "debian-linux" }, &.{ .fg_red, .fg_white }, .fg_red, .fg_red),
    LogoInfo.init(&.{"septor"}, &.{ .fg_blue, .fg_white, .fg_blue }, null, null),
    LogoInfo.init(&.{ "deepin", "deepin-linux" }, &.{.fg_green}, .fg_green, .fg_green),
    LogoInfo.init(&.{"desaos"}, &.{ .fg_green, .fg_white }, .fg_green, .fg_white),
    LogoInfo.init(&.{ "devuan", "devuan-linux" }, &.{.fg_magenta}, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{"semc"}, &.{ .fg_green, .fg_light_black, .fg_red }, null, null),
    LogoInfo.init(&.{"dietpi"}, &.{ .fg_green, .fg_black }, .fg_green, .fg_green),
    LogoInfo.init(&.{"dracos"}, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{ "dragonfly", "dragonfly-bsd" }, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{"scientific"}, &.{ .fg_blue, .fg_white, .fg_red }, null, null),
    LogoInfo.init(&.{"sasanqua"}, &.{ .fg_magenta, .fg_red }, null, null),
    LogoInfo.init(&.{ "draugeros", "drauger" }, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{"droidian"}, &.{ .fg_green, .fg_light_green }, .fg_green, .fg_light_green),
    LogoInfo.init(&.{"elbrus"}, &.{.fg_blue}, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"elementary"}, &.{.fg_white}, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "salient os", "salientos" }, &.{ .fg_cyan, .fg_white }, null, null),
    LogoInfo.init(&.{"elive"}, &.{ .fg_white, .fg_light_cyan, .fg_cyan }, .fg_white, .fg_cyan),
    LogoInfo.init(&.{"encryptos"}, &.{.fg_magenta}, .fg_magenta, .fg_green),
    LogoInfo.init(&.{ "endeavour", "endeavour-linux", "endeavouros", "endeavouros-linux" }, &.{ .fg_magenta, .fg_red, .fg_blue }, .fg_magenta, .fg_red),
    LogoInfo.init(&.{"salentos"}, &.{ .fg_green, .fg_red, .fg_yellow, .fg_white }, null, null),
    LogoInfo.init(&.{"endless"}, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{"enso"}, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{"eshanizedos"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"sailfish"}, &.{ .fg_blue, .fg_magenta }, null, null),
    LogoInfo.init(&.{"sabotage"}, &.{.fg_white}, .fg_blue, .fg_white),
    LogoInfo.init(&.{"evolutionos"}, &.{ .fg_green, .fg_white }, null, null),
    LogoInfo.init(&.{"sabayon"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "rosa", "rosa-linux", "rosalinux" }, &.{.fg_blue}, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "exherbo", "exherbo-linux" }, &.{ .fg_blue, .fg_white, .fg_red }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "rocky", "rocky-linux", "rockylinux" }, &.{.fg_green}, .fg_green, .fg_green),
    LogoInfo.init(&.{ "fedora", "fedora-linux" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"rhaymos"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"regolith"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{ "fedora_old", "fedora-old", "fedora-linux-old", "fedora-linux_old" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "fedora_silverblue", "fedora-silverblue", "fedora-linux-silverblue", "fedora-linux_silverblue" }, &.{ .fg_blue, .fg_white, .fg_cyan }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "fedora_kinoite", "fedora-kinoite", "fedora-linux-kinoite", "fedora-linux_kinoite" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "fedora_sericea", "fedora-sericea", "fedora-linux-sericea", "fedora-linux_sericea" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "fedora_coreos", "fedora-coreos", "fedora-linux-coreos", "fedora-linux_coreos" }, &.{ .fg_blue, .fg_white, .fg_red }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"regata"}, &.{ .fg_white, .fg_red, .fg_blue, .fg_magenta, .fg_yellow, .fg_green }, null, null),
    LogoInfo.init(&.{"feren"}, &.{.fg_blue}, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "redstar", "redstar-os", "redstaros", "redstaros-linux", "redstar-os-linux" }, &.{.fg_red}, .fg_red, .fg_red),
    LogoInfo.init(&.{"floflis"}, &.{.fg_light_cyan}, .fg_red, .fg_white),
    LogoInfo.init(&.{"freebsd"}, &.{ .fg_white, .fg_red }, .fg_red, .fg_red),
    LogoInfo.init(&.{ "redos", "red os", "red-os", "redos" }, &.{}, null, null),
    LogoInfo.init(&.{ "rhel", "redhat", "redhat-linux" }, &.{.fg_red}, .fg_red, .fg_red),
    LogoInfo.init(&.{ "frugalware", "frugalware-linux" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"funtoo"}, &.{ .fg_magenta, .fg_white }, .fg_magenta, .fg_white),
    LogoInfo.init(&.{"redcore"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"galliumos"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "garuda", "garuda-linux" }, &.{.fg_red}, .fg_red, .fg_red),
    LogoInfo.init(&.{ "reborn", "reborn os", "reborn-os", "rebornos", "rebornos-linux", "reborn-os-linux" }, &.{ .fg_black, .fg_blue, .fg_cyan }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"ravynos"}, &.{.fg_white}, null, null),
    LogoInfo.init(&.{ "gentoo", "gentoo-linux" }, &.{ .fg_magenta, .fg_white }, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{ "raspbian", "raspi", "raspberrypi", "raspberrypios" }, &.{ .fg_red, .fg_green }, .fg_red, .fg_green),
    LogoInfo.init(&.{"ghostbsd"}, &.{.fg_blue}, .fg_blue, .fg_red),
    LogoInfo.init(&.{"glaucus"}, &.{.fg_magenta}, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{"gnewsense"}, &.{.fg_blue}, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"gnome"}, &.{.fg_blue}, .fg_blue, .fg_red),
    LogoInfo.init(&.{"gnu"}, &.{.fg_white}, .fg_white, .fg_red),
    LogoInfo.init(&.{"quibian"}, &.{ .fg_yellow, .fg_white }, null, null),
    LogoInfo.init(&.{"qubes"}, &.{ .fg_blue, .fg_magenta }, null, null),
    LogoInfo.init(&.{"grapheneos"}, &.{.fg_white}, .fg_white, .fg_blue),
    LogoInfo.init(&.{"grombyang"}, &.{ .fg_blue, .fg_green, .fg_red }, .fg_blue, .fg_green),
    LogoInfo.init(&.{"q4os"}, &.{ .fg_blue, .fg_red }, null, null),
    LogoInfo.init(&.{"pureos"}, &.{ .fg_green, .fg_white }, null, null),
    LogoInfo.init(&.{"haiku"}, &.{ .fg_red, .fg_yellow, .fg_white, .fg_green }, .fg_red, .fg_yellow),
    LogoInfo.init(&.{"puppy"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"hamonikr"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"hardclanz"}, &.{ .fg_blue, .fg_white, .fg_red }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"puffos"}, &.{ .fg_yellow, .fg_white }, null, null),
    LogoInfo.init(&.{"hash"}, &.{}, null, null),
    LogoInfo.init(&.{"postmarketos"}, &.{ .fg_green, .fg_white }, null, null),
    LogoInfo.init(&.{"huayra"}, &.{.fg_white}, .fg_white, .fg_blue),
    LogoInfo.init(&.{"hybrid"}, &.{ .fg_blue, .fg_light_blue }, .fg_light_blue, .fg_blue),
    LogoInfo.init(&.{"hydroos"}, &.{.fg_red}, .fg_red, .fg_green),
    LogoInfo.init(&.{"porteus"}, &.{ .fg_cyan, .fg_white }, null, null),
    LogoInfo.init(&.{"hyperbola"}, &.{.fg_light_black}, .fg_light_black, .fg_white),
    LogoInfo.init(&.{ "pop", "popos", "pop_os", "pop-linux" }, &.{ .fg_cyan, .fg_white }, .fg_cyan, .fg_cyan),
    LogoInfo.init(&.{"pisi"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"instantos"}, &.{ .fg_blue, .fg_cyan }, .fg_blue, .fg_cyan),
    LogoInfo.init(&.{"pikaos"}, &.{.fg_yellow}, null, null),
    LogoInfo.init(&.{"phyos"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"ironclad"}, &.{.fg_black}, .fg_white, .fg_magenta),
    LogoInfo.init(&.{"itc"}, &.{.fg_red}, .fg_white, .fg_red),
    LogoInfo.init(&.{ "peropesis", "peropesis linux" }, &.{.fg_white}, null, null),
    LogoInfo.init(&.{"kaisen"}, &.{ .fg_red, .fg_white }, .fg_red, .fg_white),
    LogoInfo.init(&.{ "kali", "kalilinux" }, &.{ .fg_blue, .fg_light_black }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"pentoo"}, &.{ .fg_magenta, .fg_white }, null, null),
    LogoInfo.init(&.{"kaos"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"kernelos"}, &.{ .fg_red, .fg_magenta }, null, null),
    LogoInfo.init(&.{ "kde", "kde-neon", "kde neon" }, &.{.fg_green}, null, null),
    LogoInfo.init(&.{"kibojoe"}, &.{ .fg_green, .fg_white, .fg_blue }, .fg_green, .fg_white),
    LogoInfo.init(&.{ "kiss", "kiss-linux", "kisslinux" }, &.{ .fg_magenta, .fg_white, .fg_blue }, .fg_magenta, .fg_blue),
    LogoInfo.init(&.{"kogaion"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"korora"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "krassos", "krass" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"pengwin"}, &.{ .fg_magenta, .fg_light_magenta, .fg_magenta }, null, null),
    LogoInfo.init(&.{ "kubuntu", "kubuntu-linux", "kde-ubuntu" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"lainos"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "langitketujuh", "l7" }, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_blue),
    LogoInfo.init(&.{"laxeros"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"lede"}, &.{ .fg_blue, .fg_white }, .fg_blue, .fg_white),
    LogoInfo.init(&.{"libreelec"}, &.{ .fg_green, .fg_yellow, .fg_white, .fg_cyan, .fg_magenta }, .fg_green, .fg_yellow),
    LogoInfo.init(&.{"pearos"}, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }, null, null),
    LogoInfo.init(&.{ "linspire", "lindows" }, &.{ .fg_blue, .fg_green }, .fg_blue, .fg_green),
    LogoInfo.init(&.{"pclinuxos"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "pcbsd", "trueos" }, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"pardus"}, &.{ .fg_blue, .fg_cyan }, null, null),
    LogoInfo.init(&.{ "linuxlite", "linux lite", "linux_lite" }, &.{ .fg_yellow, .fg_white }, .fg_yellow, .fg_white),
    LogoInfo.init(&.{"parch"}, &.{ .fg_blue, .fg_white, .fg_red }, null, null),
    LogoInfo.init(&.{ "parabola", "parabola-gnulinux" }, &.{.fg_magenta}, .fg_magenta, .fg_magenta),
    LogoInfo.init(&.{"panwah"}, &.{ .fg_white, .fg_red, .fg_black }, null, null),
    LogoInfo.init(&.{"pacbsd"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{ "live raizo", "live_raizo" }, &.{.fg_yellow}, .fg_yellow, .fg_white),
    LogoInfo.init(&.{ "osmc", "open source media center" }, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"lmde"}, &.{ .fg_green, .fg_white }, .fg_green, .fg_white),
    LogoInfo.init(&.{ "locos", "loc-os", "loc-os linux" }, &.{ .fg_black, .fg_yellow, .fg_white }, .fg_yellow, .fg_red),
    LogoInfo.init(&.{"lunar"}, &.{ .fg_blue, .fg_white, .fg_yellow }, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "macos", "mac" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }, .fg_yellow, .fg_green),
    LogoInfo.init(&.{"orchid"}, &.{ .fg_white, .fg_magenta, .fg_magenta }, .fg_white, .fg_magenta),
    LogoInfo.init(&.{ "macos2", "mac2" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }, .fg_yellow, .fg_green),
    LogoInfo.init(&.{ "oracle", "oracle linux", "oracle linux server" }, &.{.fg_red}, .fg_red, .fg_white),
    LogoInfo.init(&.{ "macos3", "mac3" }, &.{ .fg_green, .fg_yellow, .fg_red, .fg_magenta, .fg_blue }, .fg_yellow, .fg_green),
    LogoInfo.init(&.{"mainsailos"}, &.{.fg_red}, null, null),
    LogoInfo.init(&.{"opnsense"}, &.{.fg_white}, null, null),
    LogoInfo.init(&.{"mageia"}, &.{ .fg_cyan, .fg_white }, .fg_cyan, .fg_white),
    LogoInfo.init(&.{ "openmandriva", "open-mandriva", "open_mandriva", "openmandriva lx" }, &.{.fg_blue}, .fg_blue, .fg_blue),
    LogoInfo.init(&.{ "opensuse_slowroll", "opensuse-slowroll", "opensuse-tumbleweed-slowroll" }, &.{.fg_white}, .fg_green, .fg_green),
    LogoInfo.init(&.{ "magpieos", "magpie" }, &.{ .fg_green, .fg_red, .fg_yellow, .fg_magenta }, .fg_green, .fg_red),
    LogoInfo.init(&.{ "mandriva", "mandrake" }, &.{ .fg_blue, .fg_yellow }, .fg_blue, .fg_yellow),
    LogoInfo.init(&.{ "manjaro", "manjaro-linux", "manjarolinux", "manjaro-arm" }, &.{.fg_green}, .fg_green, .fg_green),
    LogoInfo.init(&.{ "opensuse_tumbleweed", "open_suse_tumbleweed", "opensuse-tumbleweed", "open-suse-tumbleweed", "suse_tumbleweed", "suse-tumbleweed", "opensusetumbleweed" }, &.{.fg_white}, .fg_green, .fg_green),
    LogoInfo.init(&.{ "massos", "mass" }, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{ "matuusos", "matuus" }, &.{ .fg_yellow, .fg_red }, .fg_yellow, .fg_red),
    LogoInfo.init(&.{"maui"}, &.{.fg_cyan}, .fg_cyan, .fg_white),
    LogoInfo.init(&.{"mauna"}, &.{ .fg_blue, .fg_cyan }, null, null),
    LogoInfo.init(&.{ "opensuse_leap", "open_suse_leap", "opensuse-leap", "open-suse-leap", "suse_leap", "suse-leap", "opensuseleap" }, &.{.fg_white}, .fg_green, .fg_green),
    LogoInfo.init(&.{"mer"}, &.{.fg_blue}, .fg_blue, .fg_white),
    LogoInfo.init(&.{ "opensuse-microos", "opensuse_microos" }, &.{.fg_green}, null, null),
    LogoInfo.init(&.{ "opensuse", "open_suse", "open-suse" }, &.{ .fg_green, .fg_white }, .fg_green, .fg_green),
    LogoInfo.init(&.{"openstage"}, &.{ .fg_green, .fg_white }, null, null),
    LogoInfo.init(&.{"openmamba"}, &.{ .fg_white, .fg_green }, null, null),
    LogoInfo.init(&.{"openindiana"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"mos"}, &.{ .fg_cyan, .fg_blue }, null, null),
    LogoInfo.init(&.{"msys2"}, &.{ .fg_magenta, .fg_white, .fg_red }, .fg_magenta, .fg_red),
    LogoInfo.init(&.{"openeuler"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{"openbsd"}, &.{ .fg_yellow, .fg_white, .fg_cyan, .fg_red }, .fg_yellow, .fg_white),
    LogoInfo.init(&.{"mx2"}, &.{.fg_white}, .fg_blue, .fg_cyan),
    LogoInfo.init(&.{"namib"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"nekos"}, &.{ .fg_yellow, .fg_white, .fg_red }, null, null),
    LogoInfo.init(&.{"neptune"}, &.{ .fg_white, .fg_white }, null, null),
    LogoInfo.init(&.{"netrunner"}, &.{ .fg_blue, .fg_white }, null, null),
    LogoInfo.init(&.{ "openkylin", "open-kylin" }, &.{ .fg_green, .fg_white }, .fg_green, .fg_white),
    LogoInfo.init(&.{ "nixos", "nix", "nixos-linux", "nix-linux" }, &.{ .fg_blue, .fg_cyan }, null, null),
    LogoInfo.init(&.{"omnios"}, &.{ .fg_white, .fg_yellow, .fg_light_black }, null, null),
    LogoInfo.init(&.{"obrevenge"}, &.{ .fg_red, .fg_white }, null, null),
    LogoInfo.init(&.{"obarun"}, &.{ .fg_cyan, .fg_white }, null, null),
    LogoInfo.init(&.{"netbsd"}, &.{ .fg_magenta, .fg_white }, .fg_magenta, .fg_white),
    LogoInfo.init(&.{ "nobara", "nobara-linux" }, &.{.fg_white}, .fg_white, .fg_white),
    LogoInfo.init(&.{"nomadbsd"}, &.{.fg_blue}, .fg_blue, .fg_white),
    LogoInfo.init(&.{"nurunner"}, &.{ .fg_blue, .fg_white }, null, null),
};
